version: '3'
services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - oceanicex-network
    volumes:
      - .:/oceanicex
    links:
      - mongo
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - "4000:4000"
    expose:
      - "4000"
    networks:
      - oceanicex-network
    volumes:
      - .:/oceanicex
  admin:
    container_name: admin
    restart: always
    build:
      context: .
      dockerfile: admin.dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - oceanicex-network
    volumes:
      - .:/oceanicex
networks:
  oceanicex-network:
    external: true
