version: '3'
services:
  api:
    network_mode: host
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - /hndmEx/acervo:/hndmEx/acervo
      - .:/oceanicex
  app:
    network_mode: host
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - "4000:4000"
    expose:
      - "4000"
    volumes:
      - .:/oceanicex
  admin:
    network_mode: host
    container_name: admin
    restart: always
    build:
      context: .
      dockerfile: admin.dockerfile
    ports:
      - "4050:4050"
    expose:
      - "4050"
    volumes:
      - /hndmEx/acervo:/hndmEx/acervo
      - .:/oceanicex
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
    expose:
      - "27018"
    networks:
      - oceanicex-network
    volumes:
      - /hndmEx/mongo:/data/db
networks:
  oceanicex-network:
    external: true